package:
  name: plugin1
  version: 0.0.1

build:
  number: 0

requirements:
  build:
    -python
  run:
    - python
    - pluggy
test:
  imports:
    - plugin1
about:
  summary: This is a simple meta-package
